name: Github Action for Assignment 2 CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo start
        run: echo "Running GitHub Action..."
      - name: Step 2 - Check success or fail
        run: |
          echo "Checking branch name..."
          if [[ $GITHUB_HEAD_REF == hw1-f ]]; then
            echo "This is a fail test"
            exit 1
          else
            echo "This is a pass test"
          fi
